version: '3.7'
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: vollmed_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password